version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      all-actions:
        patterns: [ "*" ]

  - package-ecosystem: "composer"
    directory: "/"
    ignore: 
      - dependency-name: "phpolar/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/"
    allow:
      - dependency-name: "phpolar/*"
    schedule:
      interval: "cron"
      cronjob: "30 2 * * 1"
