<!DOCTYPE html>
<?php

use Phpolar\Example\PeopleList;

/**
 * @var PeopleList $view
 */
$view = $this;
?>
<html lang="en" data-theme="light">

<head>
    <title>MyApp People List</title>
    <meta charset="utf-8" />
    <meta name="theme-color" content="#ffffff" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Some Dev" />
    <meta name="description" content="A PHPolar Example App" />
    <meta name="keywords" content="demo,example,microframework" />
    <link rel="icon" href="/resources/images/logo.svg" />
    <link rel="apple-touch-icon" href="/resources/images/logo.svg" />
    <link rel="stylesheet" href="/resources/css/pico.classless.min.css" />
    <link rel="stylesheet" href="/resources/css/overrides.css" />
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="/" arial-label="Back Home">
                        <img width="48px" height="48px" src="/resources/images/logo.svg" alt="brand icon" />
                    </a>
                </li>
                <li><strong>Example App</strong></li>
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <h1>List of People</h1>
            <nav>
                <ul>
                    <li>
                        <a href="/person/form"><strong>Add a person</strong></a>
                    </li>
                </ul>
            </nav>
            <?php if (count($view->people) === 0) : ?>
                No results
            <?php else : ?>
                <table>
                    <thead>
                        <tr>
                            <?php foreach ($view->people[0] as $propName => $propValue) : ?>
                                <th><?= $view->people[0]->getColumnName($propName) ?></th>
                            <?php endforeach ?>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($view->people as $person) : ?>
                            <tr>
                                <?php foreach ($person as $cell) : ?>
                                    <td><?= $cell instanceof DateTimeInterface ? $cell->format(DATE_RFC3339) : $cell ?></td>
                                <?php endforeach ?>
                                <td>
                                    <form action="/person/delete/<?= $person->getPrimaryKey() ?>" method="post">
                                        <button data-style="danger" type="submit">X</button>
                                    </form>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            <?php endif ?>
        </section>
    </main>
    <footer>
        <nav>
            <ul>
                <li><strong>Phpolar</strong> - mimimal PHP</li>
                <li>&copy; <?= (new DateTimeImmutable("now"))->format("Y") ?></li>
            </ul>
        </nav>
    </footer>
</body>

</html>