<!DOCTYPE html>
<html>

<head>
    <title>MyApp People List</title>
    <meta charset="utf-8" />
    <meta name="theme-color" content="#ffffff" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Some Dev" />
    <meta name="description" content="A PHPolar Example App" />
    <meta name="keywords" content="demo,example,microframework" />
    <link rel="icon" href="/resources/images/phpolar.svg" />
    <link rel="apple-touch-icon" href="/resources/images/phpolar.svg" />
    <link rel="icon" href="/resources/images/phpolar.svg" />
    <link rel="stylesheet" href="/resources/stylesheets/style.css" />
</head>

<body>
    <main>
        <header>
            <aside class="success">
                <h1>Person Saved</h1>
            </aside>
        </header>
        <a href="/">Go to list</a>
    </main>
</body>

</html>