<!DOCTYPE html>
<html lang="en" data-theme="light">

<head>
    <title>MyApp People List</title>
    <meta charset="utf-8" />
    <meta name="theme-color" content="#ffffff" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Some Dev" />
    <meta name="description" content="A PHPolar Example App" />
    <meta name="keywords" content="demo,example,microframework" />
    <link rel="icon" href="/resources/images/logo.svg" />
    <link rel="apple-touch-icon" href="/resources/images/logo.svg" />
    <link rel="stylesheet" href="/resources/css/pico.classless.min.css" />
    <link rel="stylesheet" href="/resources/css/overrides.css" />
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="/" arial-label="Back Home">
                        <img width="48px" height="48px" src="/resources/images/logo.svg" alt="brand icon" />
                    </a>
                </li>
                <li><strong>Example App</strong></li>
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <h1><ins>Person Saved &#9989;</ins></h1>
            <a href="/">Go to list</a>
        </section>
    </main>
    <footer>
        <nav>
            <ul>
                <li><strong>Phpolar</strong> - mimimal PHP</li>
                <li>&copy; <?= (new DateTimeImmutable("now"))->format("Y") ?></li>
            </ul>
        </nav>
    </footer>
</body>

</html>