name: Dependabot auto-merge
on:
  pull_request:
    branches: [ main ]
    paths:
      - composer.lock

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-24.04
    if: github.event.pull_request.user.login == 'dependabot[bot]' || github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2.3.0
      - uses: actions/checkout@v4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR if not already approved
        run: |
          gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "$PR_URL"
          else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
      - name: Enable auto-merge for Dependabot PRs of dev dependencies
        if: |
          contains(fromJSON('["version-update:semver-patch","version-update:semver-minor"]'), steps.dependabot-metadata.outputs.update-type) &&
          contains('direct:development', steps.dependabot-metadata.outputs.dependency-type)
        run: gh pr merge --auto --merge "$PR_URL"
      - name: Enable auto-merge for Dependabot PRs of prod dependencies
        if: |
          contains(fromJSON('["version-update:semver-patch","version-update:semver-minor"]'), steps.dependabot-metadata.outputs.update-type) &&
          contains('direct:production', steps.dependabot-metadata.outputs.dependency-type)
        run: gh pr merge --auto --merge "$PR_URL"
