name: Dependabot Pull Request Auto Merge
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'composer.lock'
permissions:
  contents: write
  pull-requests: write
jobs:
  dependabot_auto_merge:
    uses: phpolar/github-workflows/.github/workflows/auto-merge.yml@v1
    secrets: inherit
  dependabot_auto_merge_phpolar:
    uses: phpolar/github-workflows/.github/workflows/auto-merge-phpolar-deps.yml@v1
    secrets: inherit
  dependabot_auto_merge_php-contrib:
    uses: phpolar/github-workflows/.github/workflows/auto-merge-php-contrib-deps.yml@v1
    secrets: inherit
  dependabot_auto_merge_phpunit:
    uses: phpolar/github-workflows/.github/workflows/phpunit-auto-merge.yml@v1
    secrets: inherit
