name: Prod Upgrade Release
on:
  schedule:
    # every Monday at 3:00AM UTC
    - cron: '0 3 * * 1'
permissions:
  contents: write
jobs:
  prod_upgrade_release:
    uses: phpolar/github-workflows/.github/workflows/prod-upgrade-release.yml@v1
    secrets: inherit
